#if you are running this power shell script
#change the path acoording to the location of files on your system
$target_file = "$HOME\projects\education\udemy\snowflake\single_query_run.bat"
$target_results = "$HOME\projects\education\udemy\snowflake\concurrent_query_res\"

Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out1.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out2.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out3.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out4.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out5.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out6.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out7.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out8.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out9.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out10.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out11.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out12.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out13.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out14.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out15.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out16.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out17.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out18.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out19.txt"
Start-Process -FilePath $target_file -RedirectStandardOutput "$target_results\out20.txt"
